# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dayoon Ko
tagline:          'A Jekyll theme'
description:      'Seoul, Korea <br/>dayoon.ko@vision.snu.ac.kr <br/>https://github.com/dayoon-ko'
url:              http://dayoon-ko.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
plugins:          [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
